name: UHCPlugin
main: io.github.darkknight8034.uhcplugin.Main
author: DarkKnight8034
version: 1.0
api-version: 1.18
description: Plugin for playing UHC
commands:
  start:
    description: Relocates players, moves world border, and sets gamemode to hardcore. Starts the game.
  end:
    description: Brings players back to spawn, turns off harcore mode. Ends the game.
  recreate:
    description: Creates a new game with the same world as last time
