game:
  start:
    # Generates new world when starting a game
    randomWorld: true
    # Deletes generated world when game ends
    deleteWorld: true
  end:
    returnToLobby: true
# Name of lobby world
# Will go to first world if game.end.returnToLobby is true but no world name is provided
lobby: 
discord:
  eventPath:
    