name: UHCPlugin
main: io.github.darkknight8034.uhcplugin.Main
author: DarkKnight8034
version: 1.0
api-version: 1.17
description: Plugin for playing UHC
commands:
  relocate:
    description: Spreads players randomly within given area around (0, 0)
  start:
    description: Relocates players, moves world border, and sets gamemode to hardcore. Starts the game.
  end:
    description: Brings players back to spawn, turns off harcore mode. Ends the game.
  test:
    description: testing